// <auto-generated />
using System;
using MicroExercise.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroExercise.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530173523_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MicroExercise.Core.Entities.ExercisePool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExerciseTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTypeId");

                    b.HasIndex("UserId", "IsActive", "SortOrder");

                    b.ToTable("ExercisePool", (string)null);
                });

            modelBuilder.Entity("MicroExercise.Core.Entities.ExerciseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultTrackingType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExerciseTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultTrackingType = "Reps",
                            Name = "Push-ups"
                        },
                        new
                        {
                            Id = 2,
                            DefaultTrackingType = "Reps",
                            Name = "Pull-ups"
                        },
                        new
                        {
                            Id = 3,
                            DefaultTrackingType = "Reps",
                            Name = "Bodyweight Squats"
                        },
                        new
                        {
                            Id = 4,
                            DefaultTrackingType = "Reps",
                            Name = "KB Swings"
                        },
                        new
                        {
                            Id = 5,
                            DefaultTrackingType = "Reps",
                            Name = "Lunges"
                        },
                        new
                        {
                            Id = 6,
                            DefaultTrackingType = "Seconds",
                            Name = "Dead Hang"
                        },
                        new
                        {
                            Id = 7,
                            DefaultTrackingType = "Seconds",
                            Name = "Plank"
                        },
                        new
                        {
                            Id = 8,
                            DefaultTrackingType = "Seconds",
                            Name = "Wall Sit"
                        });
                });

            modelBuilder.Entity("MicroExercise.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Demo User",
                            Email = "demo@microburst.local"
                        });
                });

            modelBuilder.Entity("MicroExercise.Core.Entities.WorkoutLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExercisePoolId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExercisePoolId", "Timestamp");

                    b.ToTable("WorkoutLogs", (string)null);
                });

            modelBuilder.Entity("MicroExercise.Core.Entities.ExercisePool", b =>
                {
                    b.HasOne("MicroExercise.Core.Entities.ExerciseType", "ExerciseType")
                        .WithMany("PoolEntries")
                        .HasForeignKey("ExerciseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MicroExercise.Core.Entities.User", "User")
                        .WithMany("Pool")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExerciseType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MicroExercise.Core.Entities.WorkoutLog", b =>
                {
                    b.HasOne("MicroExercise.Core.Entities.ExercisePool", "ExercisePool")
                        .WithMany("Logs")
                        .HasForeignKey("ExercisePoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExercisePool");
                });

            modelBuilder.Entity("MicroExercise.Core.Entities.ExercisePool", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("MicroExercise.Core.Entities.ExerciseType", b =>
                {
                    b.Navigation("PoolEntries");
                });

            modelBuilder.Entity("MicroExercise.Core.Entities.User", b =>
                {
                    b.Navigation("Pool");
                });
#pragma warning restore 612, 618
        }
    }
}
